sudo: required
services:
    - docker

before_install:
    - docker build -t michal2612/docker-react:latest -f Dockerfile.dev .

script:
    - docker run michal2612/docker-react:latest -d npm run test -- --coverage